# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build all formats
formats:  all

# Specify Python requirements
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
