name: Continuous Integration

on:
  push:
    paths: 
      - 'src/tfc/**'
      - 'tests/**'
      - 'setup.py'
  
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: "python -m pip install black"

      - name: lint
        run: "python -m black --line-length 100 --check ./src/tfc"

      - run: "sudo apt-get update && sudo apt-get install -y gcc g++"
      - run: python -m pip install wheel setuptools numpy pytest pybind11 mypy
      - run: python setup.py bdist_wheel
      - run: pip install ./dist/*.whl

      - name: python tests
        run: pytest tests
